---
- name: Install NVM
  become: true
  become_user: ec2-user
  shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
  tags:
    - nvm

- name: Add NVM configuration to bashrc
  become: true
  become_user: ec2-user
  lineinfile:
    path: /home/ec2-user/.bashrc
    line: |
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
      [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
    state: present
  tags:
    - bashrc

- name: Install Node.js using NVM
  become: true
  become_user: ec2-user
  shell: source ~/.bashrc && nvm install node
  tags:
    - node

- name: Install mgeneratejs
  become: true
  become_user: ec2-user
  command: npm install -g mgeneratejs
  tags:
    - mgeneratejs

- name: "Copy Party File"
  copy:
    src: "../files/party.json"
    dest: "/data/party.json"
    owner: ec2-user
    group: ec2-user
    mode: "u=rw,g=r,o=r"
  become: true